# Generated by Django 4.0.5 on 2022-06-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_myuser_email_myuser_password_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
